on:
  push:
    branches:
      - main

name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: appleboy/ssh-action@master
      with:
        host: "50.17.212.123"
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          cd web-client
          git pull

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: "50.17.212.123"
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          docker-compose up -d --build frontend

    - name: Cleanup
      uses: appleboy/ssh-action@master
      with:
        host: "50.17.212.123"
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          docker image prune -a -f
          docker system prune -f --volumes

