on:
  push:
    branches:
      - main

name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: appleboy/ssh-action@master
      with:
        host: "50.17.212.123"
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          sudo pkill node || true
          cd web-client
          git stash
          git pull

    - name: Start
      uses: appleboy/ssh-action@master
      with:
        host: "50.17.212.123"
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          cd web-client
          nohup npm start &> /dev/null &
